import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import { PGlite } from '@electric-sql/pglite';
import { pgcrypto } from '@electric-sql/pglite/contrib/pgcrypto';
const db = new PGlite({ extensions: { pgcrypto } });
const value = async (sql, args = []) => (await db.query(sql, args)).rows[0].result;
const migration = async name => db.exec(await readFile(new URL('../supabase/migrations/' + name + '.sql', import.meta.url), 'utf8'));
try {
  await db.exec('create role anon; create role authenticated;');
  await migration('20260917214744_shared_studio_without_accounts');
  await migration('20260918185010_studio_pin_access');
  await db.query('select shared_studio.set_pin($1)', ['7531']);
  let before = await value('select shared_studio.snapshot() as result');
  const actor = before.members[0].user_id, channel = before.channels[0].id;
  let token = (await value('select public.studio_pin_unlock($1) as result', ['7531'])).access_token;
  const mutate = (operation, payload) => value('select public.studio_pin_mutate($1,$2,$3,$4) as result', [token, actor, operation, JSON.stringify(payload)]);
  const base = { channel_id: channel, due_date: '2026-10-06', title: 'Calendar test', content_type: 'comic', initial_status: 'scheduled' };
  before = await mutate('add_item', base);
  await migration('20261005181755_studio_calendar_times');
  await db.exec('set role anon');
  const board = await value('select public.studio_pin_snapshot($1) as result', [token]);
  assert.equal(board.items.length, before.items.length);
  assert.equal(board.items.every(item => item.upload_time === null), true);
  assert.deepEqual(board.steps.toSorted((a,b) => a.stage.localeCompare(b.stage)), before.steps.toSorted((a,b) => a.stage.localeCompare(b.stage))); assert.deepEqual(board.members, before.members);
  for (const sql of ['select shared_studio.snapshot()', "select shared_studio.mutate(null,'add_item','{}')", 'select public.studio_shared_snapshot()', 'select * from shared_studio.items']) await assert.rejects(db.query(sql), /permission denied/);
  await assert.rejects(value('select public.studio_pin_snapshot($1) as result', ['invalid']), /team PIN|session ended/);
  let result = await mutate('add_item', { ...base, upload_time: '11:00' });
  let item = result.items.find(i => i.upload_time === '11:00');
  assert.ok(item);
  await assert.rejects(mutate('add_item', { ...base, upload_time: '11:00' }), /already has an upload/);
  for (const time of ['24:00','11:61','1:00','11:00:00']) await assert.rejects(mutate('add_item', { ...base, upload_time: time }), /upload time/);
  result = await mutate('edit_item', { ...base, item_id: item.id, version: item.version, title: 'Old frontend edit' });
  item = result.items.find(i => i.id === item.id);
  assert.equal(item.upload_time, '11:00', 'Old client omission preserves time');
  await assert.rejects(mutate('edit_item', { ...base, item_id: item.id, version: 1, upload_time: '12:00' }), /Someone updated/);
  result = await mutate('edit_item', { ...base, item_id: item.id, version: item.version, upload_time: null });
  item = result.items.find(i => i.id === item.id); assert.equal(item.upload_time, null);
  result = await mutate('add_item', { ...base, upload_time: '11:00' });
  const old = result.items.find(i => i.upload_time === null);
  await assert.rejects(mutate('edit_item', { ...old, item_id: old.id, upload_time: '11:00' }), /already has an upload/);
  const other = before.channels[1];
  if (other) assert.ok((await mutate('add_item', { ...base, channel_id: other.id, upload_time: '11:00' })).items.some(i => i.channel_id === other.id && i.upload_time === '11:00'));
  const secondToken = (await value('select public.studio_pin_unlock($1) as result', ['7531'])).access_token;
  const secondBoard = await value('select public.studio_pin_snapshot($1) as result', [secondToken]);
  assert.equal(secondBoard.items.some(i => i.upload_time === '11:00'), true, 'Another browser sees saved time');
  console.log('PASS: calendar migration preserves records and PIN, validates slots, rejects collisions/stale edits and shares saves.');
} finally { await db.close(); }
