import assert from 'node:assert/strict';
import { mkdtemp, readFile, rm } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { PGlite } from '@electric-sql/pglite';

// Real PostgreSQL persistence with no auth schema or user accounts at all.
const directory = await mkdtemp(join(tmpdir(), 'ginduyah-shared-'));
let db = new PGlite(directory);
let checks = 0;
const check = (actual, expected, message) => { assert.deepEqual(actual, expected, message); checks++; };
const rejects = async (fn, match) => { await assert.rejects(fn, match); checks++; };
const value = async (query, args = []) => (await db.query(query, args)).rows[0].result;
const snapshot = () => value('select public.studio_shared_snapshot() as result');
const mutate = (actor, operation, payload) => value('select public.studio_shared_mutate($1, $2, $3) as result', [actor, operation, JSON.stringify(payload)]);
try {
  await db.exec('create role anon; create role authenticated;');
  const migration = await readFile(new URL('../supabase/migrations/20260917214744_shared_studio_without_accounts.sql', import.meta.url), 'utf8');
  await db.exec(migration);
  await db.exec('set role anon');
  let board = await snapshot();
  check(board.members.length, 1, 'An anonymous visitor opens the existing shared board.');
  check(board.channels.length, 2, 'Both initial channels exist without account setup.');
  const quatic = board.members[0].user_id;
  const ginduyah = board.channels.find(c => c.name === 'ginduyah');
  const nba = board.channels.find(c => c.name === 'NBA comics');
  check([ginduyah.comic_goal, ginduyah.post_goal], [2, 1], 'Daily defaults match the request.');
  await rejects(() => db.query('select * from shared_studio.items'), /permission denied/);
  await rejects(() => db.query("update shared_studio.workspaces set name = 'Bypass'"), /permission denied/);
  await rejects(() => mutate(null, 'add_member', { display_name: 'Nobody' }), /Choose an active/);
  await rejects(() => mutate(quatic, 'remove_member', { user_id: quatic, version: 1 }), /at least one/);
  board = await mutate(quatic, 'add_member', { display_name: 'Bob' });
  const bob = board.members.find(m => m.display_name === 'Bob').user_id;
  check(board.workspace.revision, 2, 'A save returns its committed snapshot and newer revision.');
  await rejects(() => mutate(quatic, 'add_member', { display_name: ' bob ' }), /already on the roster/);
  await rejects(() => mutate(quatic, 'add_member', { display_name: '   ' }), /check constraint/);
  board = await mutate(bob, 'edit_member', { user_id: quatic, display_name: 'Quatic4', version: 1 });
  check(board.members.find(m => m.user_id === quatic).display_name, 'Quatic4', 'Roster changes work without owner authentication.');
  await rejects(() => mutate(quatic, 'edit_member', { user_id: quatic, display_name: 'Stale', version: 1 }), /Someone updated/);
  board = await mutate(quatic, 'add_item', { channel_id: ginduyah.id, title: 'Shared comic', content_type: 'comic', due_date: '2026-09-17', initial_status: 'planned' });
  const item = board.items[0];
  check(item.submitted_by, quatic, 'Credit uses the chosen roster label.');
  check(board.steps.length, 4, 'A new submission has all four stages.');
  // Another fresh caller sees committed data, with no login or local storage.
  await db.exec('reset role; set role authenticated;');
  check((await snapshot()).items[0].title, 'Shared comic', 'Another viewer sees the shared submission.');
  await db.exec('reset role; set role anon;');
  await rejects(() => mutate(bob, 'set_step', { item_id: item.id, stage: 'scheduled', done: true, version: 1 }), /edit finished/);
  board = await mutate(quatic, 'set_step', { item_id: item.id, stage: 'voiceover', assigned_to: bob, version: 1 });
  board = await mutate(bob, 'set_step', { item_id: item.id, stage: 'voiceover', done: true, version: 2 });
  check(board.steps.find(s => s.stage === 'voiceover').completed_by, bob, 'Completed work is credited to the selected name.');
  await rejects(() => mutate(quatic, 'set_step', { item_id: item.id, stage: 'voiceover', done: false, version: 2 }), /Someone updated/);
  board = await mutate(quatic, 'set_step', { item_id: item.id, stage: 'script', assigned_to: bob, version: 1 });
  board = await mutate(quatic, 'remove_member', { user_id: bob, version: 1 });
  check(board.members.find(m => m.user_id === bob).active, false, 'Removed members leave the name picker.');
  check(board.steps.find(s => s.stage === 'script').assigned_to, null, 'Removal releases unfinished assignments.');
  check(board.steps.find(s => s.stage === 'voiceover').completed_by, bob, 'Removal preserves completion credits.');
  check(board.activity.some(a => a.actor_id === bob && a.actor_name === 'Bob'), true, 'History retains the original name.');
  await rejects(() => mutate(bob, 'add_item', {}), /Choose an active/);
  await rejects(() => mutate(quatic, 'set_step', { item_id: item.id, stage: 'script', assigned_to: bob, version: 3 }), /active team member/);
  board = await mutate(quatic, 'restore_member', { user_id: bob, version: 2 });
  board = await mutate(bob, 'edit_member', { user_id: bob, display_name: 'Bobby', version: 3 });
  check(board.members.find(m => m.user_id === bob).display_name, 'Bobby', 'Restored names can be edited.');
  check(board.steps.find(s => s.stage === 'voiceover').completed_by, bob, 'Renames preserve stable credit IDs.');
  board = await mutate(bob, 'set_step', { item_id: item.id, stage: 'voiceover', done: false, version: 3 });
  board = await mutate(bob, 'set_step', { item_id: item.id, stage: 'edit', done: true, version: 1 });
  board = await mutate(quatic, 'set_step', { item_id: item.id, stage: 'scheduled', done: true, version: 1 });
  await rejects(() => mutate(bob, 'set_step', { item_id: item.id, stage: 'edit', done: false, version: 2 }), /Reopen scheduling/);
  board = await mutate(quatic, 'edit_item', { item_id: item.id, version: 1, title: 'Updated comic', due_date: '2026-09-18', content_type: 'comic' });
  await rejects(() => mutate(bob, 'edit_item', { item_id: item.id, version: 1, title: 'Stale comic', due_date: '2026-09-18', content_type: 'comic' }), /Someone updated/);
  check((await snapshot()).items[0].title, 'Updated comic', 'A stale writer cannot overwrite newer content.');
  board = await mutate(quatic, 'set_goal', { channel_id: ginduyah.id, day: '2026-09-18', comic_goal: 3, post_goal: 2, version: 0 });
  await rejects(() => mutate(bob, 'set_goal', { channel_id: ginduyah.id, day: '2026-09-18', comic_goal: 9, post_goal: 9, version: 0 }), /Someone updated/);
  board = await mutate(bob, 'set_goal', { channel_id: ginduyah.id, day: '2026-09-18', comic_goal: 4, post_goal: 2, version: 1 });
  check(board.goals[0].comic_goal, 4, 'A refreshed target form can save.');
  check(board.channels.find(c => c.id === ginduyah.id).comic_goal, 2, 'Daily changes do not alter all future days.');
  check(board.items.filter(i => i.channel_id === nba.id).length, 0, 'Channels keep independent submissions.');
  board = await mutate(quatic, 'edit_channel', { channel_id: nba.id, version: 1, name: 'NBA studio', handle: '@nba' });
  await rejects(() => mutate(bob, 'edit_channel', { channel_id: nba.id, version: 1, name: 'Old name' }), /Someone updated/);
  await rejects(() => mutate(bob, 'add_item', { channel_id: ginduyah.id, title: 'Bad', content_type: 'comic', due_date: '2026-09-18', link: 'javascript:alert(1)' }), /check constraint/);
  await rejects(() => mutate(bob, 'delete_item', { item_id: item.id, version: 1 }), /Someone updated/);
  board = await mutate(bob, 'delete_item', { item_id: item.id, version: 2 });
  check(board.items.length, 0, 'Any selected teammate can remove a submission.');
  check(board.steps.length, 0, 'Removed submissions have no orphaned stage credits.');
  check(board.activity.some(a => a.action === 'removed' && a.title === 'Updated comic'), true, 'Removal stays in activity history.');
  const saved = await snapshot();
  await db.close();
  db = new PGlite(directory);
  await db.exec('set role anon');
  check(await snapshot(), saved, 'A new database connection sees the same persistent shared board.');
  console.log(`PASS: ${checks} shared-board checks covering no-account access, roster changes, persistence, validation, and stale edits.`);
} finally { await db.close(); await rm(directory, { recursive: true, force: true }); }
